// <auto-generated />
using System;
using KidsAreaApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KidsAreaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210113012036_modifyReceipt")]
    partial class modifyReceipt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("KidsAreaApp.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("KidsAreaApp.Models.Receipt", b =>
                {
                    b.Property<Guid>("SerialKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("BarCode")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("QrCodePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerialKey");

                    b.ToTable("Receipt");
                });

            modelBuilder.Entity("KidsAreaApp.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndReservationTme")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReceiptSerialKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartReservationTme")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReceiptSerialKey");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("KidsAreaApp.Models.Reservation", b =>
                {
                    b.HasOne("KidsAreaApp.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("KidsAreaApp.Models.Receipt", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptSerialKey");

                    b.Navigation("Customer");

                    b.Navigation("Receipt");
                });
#pragma warning restore 612, 618
        }
    }
}
